name: Flake8 your PR
on:
  push:
    branches:
      - master
jobs:
  flake8-your-pr:
    runs-on: ubuntu-latest
    steps:

      - uses: actions/checkout@v2
        with:
          ref: "${{ github.head_ref }}"
          fetch-depth: 2

      # - uses: tayfun/flake8-your-pr@master
      - uses: stefanfle/flake8-your-pr@master
        env:
          GITHUB_TOKEN: "${{ secrets.GITHUB_TOKEN }}"
